# Project information
site_name: K-Share
site_url: https://obth.github.io/k-share/
site_description: Let's promote knowledge share

# Repository
repo_name: OBTH/k-share
repo_url: https://github.com/OBTH/k-share
edit_uri: ""

# Configuration
theme:
  name: material
  features:
    - tabs
  palette:
    primary: black
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/brain
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search
  - awesome-pages

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: true

# Customization
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
