name: Publish via GitHub Pages

on:
  push:
    branchs:
      - master

jobs:
  build:
    name: Deploy pages
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip
      
      - name: Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"
      
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: python3 -m pip install -r ./requirements.txt
      
      - name: Build docs
        run: mkdocs build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          full_commit_message: ${{ github.event.head_commit.message }}
